#ifndef ENEMY_HEADER_H
#define ENEMY_HEADER_H

// The Crownroad fills every enemy slot; other areas stop at AREA_ENEMY_LIMIT.
#define MAX_ENEMIES 30
#define AREA_ENEMY_LIMIT 15

typedef enum {
    ENEMY_SKELETON = 0,
    ENEMY_GOBLIN,
    ENEMY_ZOMBIE,
    ENEMY_ORC,
    ENEMY_TROLL,
    ENEMY_GIANT,
    ENEMY_GOBLIN_KING,
    ENEMY_LICH_KING,
    ENEMY_DEMON_LORD,
    ENEMY_RED_DRAGON,
    ENEMY_TARRASQUE,
    ENEMY_CRYPT_BAT,
    ENEMY_WRAITH,
    ENEMY_CRYPT_CONJURER,
    ENEMY_PIXIE,
    ENEMY_BLIGHTED_WOLF,
    ENEMY_GIANT_SPIDER,
    ENEMY_DARK_ELF,
    ENEMY_GIANT_WURM,
    ENEMY_FOREST_TROLL,
    ENEMY_FOREST_NECROMANCER,
    ENEMY_GOBLIN_SCOUT,
    ENEMY_GOBLIN_ARCHER,
    ENEMY_GOBLIN_BOMBER,
    ENEMY_TUNNEL_SPIDER,
    ENEMY_CAVE_TROLL,
    ENEMY_HOBGOBLIN_GUARD,
    ENEMY_GOBLIN_SHAMAN,
    ENEMY_MOUNTAIN_GOBLIN_KING,
    ENEMY_ILLUSION,
    ENEMY_MERFOLK,
    ENEMY_SIREN,
    ENEMY_GIANT_CRAB,
    ENEMY_ANIMATED_STATUE,
    ENEMY_WATER_ELEMENTAL,
    ENEMY_SEA_SERPENT,
    ENEMY_DROWNED_QUEEN,
    ENEMY_RELIC_SCARABS,
    ENEMY_TEMPLE_STALKER,
    ENEMY_BLOWDART_HUNTER,
    ENEMY_VINEBOUND_GUARDIAN,
    ENEMY_SUN_PRIEST,
    ENEMY_SERPENT_SPIRIT,
    ENEMY_TREASURE_WRAITH,
    ENEMY_LUNAR_EFFIGY,
    ENEMY_MOONBOUND_SENTINEL,
    ENEMY_FALLEN_SUN_GUARDIAN,
    ENEMY_LABYRINTH_WARDEN,
    ENEMY_GIANT_RAT,
    ENEMY_BANDIT,
    ENEMY_VAMPIRE,
    ENEMY_SWAMP_DEMON,
    ENEMY_DRAKE,
    ENEMY_FIRE_ELEMENTAL,
    ENEMY_ROAD_ARCHER,
    ENEMY_HORSEMAN,
    ENEMY_ICE_WOLF,
    ENEMY_FROST_ARCHER,
    ENEMY_YETI,
    ENEMY_FROST_WRAITH,
    ENEMY_ICE_GOLEM,
    ENEMY_ICE_GIANT,
    ENEMY_POLAR_KRAKEN,
    ENEMY_SCARAB,
    ENEMY_VIPER,
    ENEMY_MUMMY,
    ENEMY_DJINN,
    ENEMY_GOLEM,
    ENEMY_DESERT_PHARAOH,
    ENEMY_FEY_TRICKSTER,
    ENEMY_GIANT_MOTH,
    ENEMY_LIVING_FLOWER,
    ENEMY_THORN_GUARDIAN,
    ENEMY_THORN_REGENT,
    ENEMY_CINDER_IMP,
    ENEMY_ASH_HOUND,
    ENEMY_OBSIDIAN_GUARDIAN,
    ENEMY_CINDER_LORD
} EnemyType;

typedef struct {
    int       x, y;
    int       active;
    EnemyType type;
    char name[32];
    int       hp, max_hp;
    int       attack, defense;
    int       experience;
    int       move_timer;
    int       is_boss;
    int       dain_fragment;
    int       frozen_turns;
    int attack_target_x, attack_target_y;
} Enemy;

#endif
