#include "test_utils.h"

int tests_run    = 0;
int tests_passed = 0;

void test_movement(void);
void test_enemy_projectiles(void);
void test_map(void);
void test_map_tiles(void);
void test_viewport(void);
void test_dungeon(void);
void test_dungeon_exit_distance(void);
void test_dungeon_exit_reachability(void);
void test_stairs_locked(void);
void test_final_dungeon_exit(void);
void test_enemy_movement_collision(void);
void test_new_dungeon_enemies(void);
void test_return_to_town_spell(void);
void test_town_tiles(void);
void test_town_healer(void);
void test_king_roads_and_castle(void);
void test_town3_royal_guards(void);
void test_rook_labyrinth(void);
void test_minotaur(void);
void test_town_map(void);
void test_town_spawn(void);
void test_cain_gift(void);
void test_harbor_road(void);
void test_island(void);
void test_temple(void);
void test_leveling(void);
void test_region_difficulty_scaling(void);
void test_items(void);
void test_classes(void);
void test_level_cache_cleared(void);
void test_return_to_town(void);
void test_forest(void);
void test_forest_travel(void);
void test_mountains(void);
void test_mountain_travel(void);
void test_coast(void);
void test_area_depths(void);
void test_coast_terrain(void);
void test_swamp(void);
void test_swamp_travel(void);
void test_route_save_migrations(void);
void test_regional_shortcuts(void);
void test_frostfell(void);
void test_frostfell_quest(void);
void test_desert(void);
void test_moonveil(void);
void test_moonveil_quest(void);
void test_ashen(void);
void test_glassdeep(void);
void test_glassdeep_quest(void);
void test_catacombs(void);
void test_castle(void);
void test_workshop(void);
void test_emberforge(void);
void test_mountain_terrain(void);
void test_dragonspine(void);
void test_elowen_quest(void);
void test_elowen_relocation(void);
void test_tavern_interior(void);
void test_dain_quest(void);
void test_dain_guild(void);
void test_alder_quest(void);
void test_mara_quest(void);
void test_quest_activation_gating(void);
void test_quest_journal(void);
void test_save_load(void);
void test_save_confirmation(void);
void test_combat_feedback(void);
void test_controls(void);

int main(void) {
    // ASSERT("sanity check true",  1 == 1);
    // ASSERT("sanity check false", 1 == 0);
    printf("=== CONR Test Suite ===\n\n");
    test_movement();
    test_enemy_projectiles();
    printf("\n");
    test_map();
    printf("\n");
    test_map_tiles();
    printf("\n");
    test_viewport();
    printf("\n");
    test_dungeon();
    printf("\n");
    test_stairs_locked();
    printf("\n");
    test_final_dungeon_exit();
    printf("\n");
    test_enemy_movement_collision();
    printf("\n");
    test_new_dungeon_enemies();
    printf("\n");
    test_return_to_town_spell();
    printf("\n");
    test_town_tiles();
    test_town_healer();
    test_king_roads_and_castle();
    test_town3_royal_guards();
    test_rook_labyrinth();
    test_minotaur();
    printf("\n");
    test_town_map();
    printf("\n");
    test_town_spawn();
    printf("\n");
    test_cain_gift();
    printf("\n");
    test_harbor_road();
    printf("\n");
    test_island();
    printf("\n");
    test_temple();
    printf("\n");
    test_forest();
    test_forest_travel();
    printf("\n");
    test_mountains();
    test_mountain_travel();
    printf("\n");
    test_mountain_terrain();
    printf("\n");
    test_dragonspine();
    printf("\n");
    test_coast();
    test_area_depths();
    printf("\n");
    test_coast_terrain();
    printf("\n");
    test_swamp();
    test_swamp_travel();
    test_route_save_migrations();
    test_regional_shortcuts();
    printf("\n");
    test_frostfell();
    test_frostfell_quest();
    printf("\n");
    test_desert();
    test_moonveil();
    test_moonveil_quest();
    test_ashen();
    test_glassdeep();
    test_glassdeep_quest();
    test_catacombs();
    test_castle();
    test_workshop();
    test_emberforge();
    printf("\n");
    test_quest_activation_gating();
    printf("\n");
    test_elowen_quest();
    test_elowen_relocation();
    printf("\n");
    test_tavern_interior();
    printf("\n");
    test_dain_quest();
    test_dain_guild();
    printf("\n");
    test_alder_quest();
    printf("\n");
    test_mara_quest();
    printf("\n");
    test_quest_journal();
    printf("\n");
    test_level_cache_cleared();
    printf("\n");
    test_return_to_town();
    printf("\n");
    test_leveling();
    printf("\n");
    test_region_difficulty_scaling();
    printf("\n");
    test_items();
    printf("\n");
    test_save_load();
    test_save_confirmation();
    printf("\n");
    test_classes();
    printf("\n");
    test_dungeon_exit_distance();
    test_dungeon_exit_reachability();
    printf("\n");
    test_combat_feedback();
    printf("\n");
    test_controls();
    printf("\n");
    REPORT();
}
